commercialhaskell/pantry

ChangeLog.md
package.yaml
pantry.cabal
src/Pantry.hs
src/Pantry/Archive.hs
src/Pantry/Hackage.hs
src/Pantry/Types.hs
test/Pantry/ArchiveSpec.hs
test/Pantry/BuildPlanSpec.hs
test/Pantry/CabalSpec.hs
test/Pantry/TreeSpec.hs
test/Pantry/TypesSpec.hs

For an example of the bugs involved here, https://github.com/commercialhaskell/stack/issues/5045.

Don't compare generated cabal files

---

src/Pantry/Internal/Stackage.hs

These are the changes necessary for the new upcoming PR into stackage that adds ability to use fallback cabal files for core packages from external repo: [commercialhaskell/core-cabal-files](https://github.com/commercialhaskell/core-cabal-files)

Stackage update

---

package.yaml
pantry.cabal
src/Pantry/Tree.hs

The only API change in `Cabal-3.2.*` that affects `pantry` is the new type signature for `runParseResult`:
```diff
-runParseResult :: ParseResult a -> ([PWarning], Either (Maybe Version, [PError])        a)
+runParseResult :: ParseResult a -> ([PWarning], Either (Maybe Version, NonEmpty PError) a)
```
Luckily, this can be adapted to without CPP by simply calling `Foldable.toList` on the returned list of `PError`s, which works on both `[]` on `NonEmpty`.
Fixes #21.

Allow building with Cabal-3.2.*

---

ChangeLog.md
package.yaml
pantry.cabal
src/Pantry.hs
src/Pantry/Types.hs
test/Pantry/BuildPlanSpec.hs
test/Pantry/TypesSpec.hs

**Description of the problem**
`pantry` expands snapshot synonyms (like `lts-X.Y` or `nightly-YYYY-MM-DD`) to a URL, using the hardcoded address of  commercialhaskell's git repository.
This basically happens in the functions `ltsSnapshotLocation` and `nightlySnapshotLocation` in [Types.hs](https://github.com/commercialhaskell/pantry/blob/master/src/Pantry/Types.hs). For instance, `lts-X.Y` expands to `https://raw.githubusercontent.com/commercialhaskell/stackage-snapshots/master/lts/X/Y.yaml`.
The hardcoded URL, however, prevents to use mirrors for snapshot locations, and mirrors are necessary in corporate environments (or really anywhere behind a firewall).
(Note: one could specify a custom URL instead of a snapshot synonym, but this can be undesirable for the following reason. In a …

Make snapshot locations configurable

---

src/Pantry/Storage.hs

Attempting to build `pantry-0.5.1.3` with `persistent-2.11` yields the following build error:
```
[10 of 19] Compiling Pantry.Storage   ( src/Pantry/Storage.hs, dist/build/Pantry/Storage.o, dist/build/Pantry/Storage.dyn_o )
src/Pantry/Storage.hs:124:1: error:
Generating Persistent entities now requires the following language extensions:
DataKinds
FlexibleInstances
Please enable the extensions by copy/pasting these lines into the top of your file:
{-# LANGUAGE DataKinds #-}
{-# LANGUAGE FlexibleInstances #-}
|
124 | share [mkPersist sqlSettings, mkMigrate "migrateAll"] [persistLowerCase|
| ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^...
```
This patch adopts the advice from the error message.

Allow building with persistent-2.11

---

ChangeLog.md
src/Pantry.hs

's3.amazonaws.com' is not meant to serve clients around the world, as it
is hosted in the US only. This causes bandwidth to be severely throttled
for non-US users. This has been observed by users in
the following issue:
https://github.com/commercialhaskell/stack/issues/2240
At some periods, bandwidth drops to effectively zero, rendering Stack
unusable. Measurements can be found here:
https://github.com/commercialhaskell/stack/issues/2240#issuecomment-761197177
'hackage.haskell.org' is served from Fastly's CDN, therefore mitigating
these issues.
-----------------
This is part of a [larger effort](https://github.com/commercialhaskell/stack/issues/2240#issuecomment-761812803) to eliminate Stack's reliance on non-CDN resources :). I see @snoyberg reverted an earlier change to move back to …

Switch back to hackage.haskell.org

---

ChangeLog.md
package.yaml
src/Hackage/Security/Client/Repository/HttpLib/HttpClient.hs
src/Pantry/HTTP.hs

Fixes https://github.com/commercialhaskell/stack/issues/5509
Tested that it works with our private hackage instance

Support basic auth

---

.azure/azure-linux-template.yml
package.yaml
pantry.cabal
stack-cabal-3.4.yaml

Expand cabal bounds

---

ChangeLog.md
package.yaml
pantry.cabal
src/Pantry/Storage.hs

Fixes the following error:
```
[10 of 19] Compiling Pantry.Storage   ( src/Pantry/Storage.hs, dist/build/Pantry/Storage.dyn_o )
src/Pantry/Storage.hs:275:8: error:
• Couldn't match type: forall env1 a1.
HasLogFunc env1 =>
ReaderT SqlBackend (RIO env1) a1 -> RIO env1 a1
with: ReaderT SqlBackend (RIO env) a -> RIO env a
Expected: SQLite.Storage
-> ReaderT SqlBackend (RIO env) a -> RIO env a
Actual: SQLite.Storage
-> forall env a.
HasLogFunc env =>
ReaderT SqlBackend (RIO env) a -> RIO env a
• In the first argument of ‘flip’, namely ‘SQLite.withStorage_’
In the first argument of ‘(=<<)’, namely
‘flip SQLite.withStorage_ action’
In the expression:
flip SQLite.withStorage_ action
=<< view (P.pantryConfigL . to P.pcStorage)
• Relevant bindings include
action :: ReaderT SqlBackend (RIO env) a …
```

Fix compatibility with GHC 9

---

ChangeLog.md
pantry.cabal
src/Pantry.hs
src/Pantry/Repo.hs
src/Pantry/Storage.hs
src/Pantry/Types.hs

Necessary for https://github.com/commercialhaskell/stack/issues/5411
Please review this carefully. I don't understand most of pantry, but this seemed like the right place to inject and my manual tests succeeded.
Stack will then run `fetchReposRaw` at a specific place for pre-fetching. So we don't really change existing API.

Improve and expose `fetchRepos`/`fetchReposRaw`

---

.azure/azure-linux-template.yml
.azure/azure-osx-template.yml
.azure/azure-pipelines.yml
.azure/azure-windows-template.yml
package.yaml
pantry.cabal
stack-ghc-922.yaml

If the upper bound on the `Cabal` dependency is relaxed to allow `Cabal-3.6.3.0`, then `pantry-0.5.4` can compile with GHC 9.2.2.
Tested by compiling `pantry` using `stack --stack-yaml=stack-ghc-922.yaml build` on Windows 11. The built `pantry` then tested by using it to build `stack` with GHC 9.2.2 on Windows 11. The built `stack` then tested by using it.

Allow compilation with nightly-2020-04-04 (GHC 9.2.2)

---

src/Pantry/Types.hs

Clears warning when building with dependency on `Cabal >= 3.4.0.0`:
~~~
src\Pantry\Types.hs:1136:3: warning: [-Wincomplete-patterns]
Pattern match(es) are non-exhaustive
In a case alternative:
Patterns of type ‘CabalSpecVersion’ not matched:
CabalSpecV3_4
CabalSpecV3_6
|
1136 |   case cabalSpecLatest of
|   ^^^^^^^^^^^^^^^^^^^^^^^^...
~~~
Makes use of `Distribution.CabalSpecVersion.cabalSpecToVersionDigits`, available from `Cabal-3.4.0.0`.

Clear a compiler warning

---

src/Pantry/Hackage.hs

Clears:
~~~
src\Pantry\Hackage.hs:45:1: warning: [-Wunused-imports]
The import of ‘System.IO’ is redundant
except perhaps to import instances from ‘System.IO’
To import instances alone, use: import System.IO()
|
45 | import System.IO (SeekMode (..)) -- Needed on GHC 8.6
~~~
The need for the import from `System.IO` is not GHC 8.6 but `rio < 0.1.16.0`.

Clear (third) compiler warning

---

src/Pantry.hs

Before:
```
Cabal file warning in/path/to/foo.cabal
```
After:
```
Cabal file warning in /path/to/foo.cabal
```

Add space in Cabal file warning

---

ChangeLog.md
package.yaml
pantry.cabal
src/Pantry.hs
src/Pantry/Hackage.hs
src/Pantry/Types.hs

This pull request proposes a relatively minor, but breaking, change to Pantry's API. There is a corresponding pull request for Stack that adopts this version of the Pantry API. There is one other package on Hackage with a dependency on Pantry - `mega-sdist`. If this pull request is accepted I will propose a pull request for that package to update it for `pantry-0.6.0`.
(EDIT: [`commercialhaskell/curator](https://github.com/commercialhaskell/curator) also depend on Pantry, but the current version of Curator compiles with this changed version of Pantry.)
The motivation for this proposal is the request at Stack issue [#5870](https://github.com/commercialhaskell/stack/issues/5870).
What is currently referred to as `HackageSecurityConfig` is better named `PackageIndexConfig`, comprising a true …

Separate true `HackageSecurityConfig` from (renamed) `PackageIndexConfig`

---

ChangeLog.md
package.yaml
pantry.cabal
src/Pantry/Types.hs

Also bumps `pantry-0.6.0` to 0.7.0 due to changed behaviour of an exported function.
Flags the default value of `hscIgnoreExpiry` in the Haddock documentation.

Fix #62 Change `defaultHackageSecurityConfig` to be consistent

---

src/Pantry/Types.hs

Stack now handles [S-536] directly (as [S-8835]), so the Pantry exception does need to refer people to Stack's repository or offer Stack's workaround.
See https://github.com/commercialhaskell/stack/pull/5950.

Fix #58 Stack now handles [S-536]

---

ChangeLog.md
package.yaml
pantry.cabal
src/Pantry.hs
src/Pantry/Archive.hs
src/Pantry/Casa.hs
src/Pantry/Hackage.hs
src/Pantry/Repo.hs
src/Pantry/Tree.hs
test/Pantry/FileSpec.hs

Like Stack, also refers to Hpack as 'Hpack' (unless referring to the command 'hpack') and refers to Cabal files as 'Cabal files' rather than '.cabal' files (unless the context is the extension to the files).
If this pull request is accepted, I will update Stack accordingly.
(As an aside, I also have a suggestion in another area that could be included in a `pantry-0.8.0`.)

Fix #69 Don't hard code "stack" as Hpack program name

---

src/Pantry.hs
src/Pantry/Types.hs

Pantry explains that exception types may be thrown from underlying libraries and that it does not attempt to wrap them. See https://hackage.haskell.org/package/pantry-0.7.1/docs/Pantry.html#g:4. However, I suggest that an exception be made for exceptions encountered while using Hpack, because package.yaml is fundamental to the user experience.
For example, rather than a user being presented by Stack with just:
~~~text
D:\Users\mike\Code\Haskell\foo\package.yaml:61:0: could not find expected ':' while scanning a simple key 
~~~
the user would be presented with:
~~~text
D:\Users\mike\Code\Haskell\foo\package.yaml:61:0: could not find expected ':' while scanning a simple key Error: [S-305]
Failed to generate a Cabal file using the Hpack library on file: …

Fix #71 Handle exceptions thrown by Hpack

---

.github/workflows/tests.yml

As things are we don't fully benefit from dependency caching, resulting in excessive build  times.
The reason for this is that the total space requirement for all the caches of our build matrix exceeds the GithHub quota of 10 GB. This results in  caches being evicted before they can ever be reused.
I usually address this by testing only the latest version of GHC on Windows / OSX, while running tests for older versions on Linux only.
**I acknowledge that it's not a perfect solution. It's a trade-off between speedy builds and coverage. You guys have to make a call whether this is the right thing to do for `pantry`.**
Impact: This PR should bring down the build time from 45m to less than 5m.

ci: Don't test all os / resolver combinations

---

package.yaml
pantry.cabal
src/Pantry.hs
src/Pantry/Types.hs
stack-cabal-3.4.yaml
stack-cabal-3.4.yaml.lock
stack-ghc-8.6.5.yaml
stack-ghc-8.6.5.yaml.lock
stack-ghc-8.8.4.yaml
stack-ghc-8.8.4.yaml.lock
stack-ghc-9.2.5.yaml
stack-ghc-9.2.5.yaml.lock
stack-ghc-9.4.3.yaml
stack-ghc-9.4.3.yaml.lock
stack-persistent-2.11.yaml
stack-persistent-2.11.yaml.lock
stack.yaml
stack.yaml.lock

For the context to this pull request see [Hpack issue #530](https://github.com/sol/hpack/issues/530), the [Hpack PR #531](https://github.com/sol/hpack/pull/531) and the alternative [Hpack PR #535](https://github.com/sol/hpack/pull/535) (on which this PR builds).
This PR is draft until such time as there is a released version of Hpack on which it relies.

Fix Hpack #530 Make use of prettier Hpack error messages

---

.github/workflows/tests.yml
stack-ghc-9.4.3.yaml

Update CI for updates to GitHub-hosted runners

---

src/Pantry.hs
src/Pantry/HPack.hs

Fixes https://github.com/commercialhaskell/stack/issues/6057.
Hpack does not over-write an existing Cabal file, if it was generated by a more recent version of Hpack. Pantry, when it is using its built-in version of Hpack, warns when this occurs but does not consider it fatal - it will go on to use the existing Cabal file that was not over-written.
This extends the warning for `Hpack.AlreadyGeneratedByNewerHpack` to include the existing advice given for `Hpack.ExistingCabalFileWasModifiedManually`, which is equally applicable.

Extend Hpack.AlreadyGeneratedByNewerHpack warning

---

.github/workflows/tests.yml
app/test-pretty-exceptions/Main.hs
app/test-pretty-exceptions/unix/PathAbsExamples.hs
app/test-pretty-exceptions/unix/System/Terminal.hsc
app/test-pretty-exceptions/windows/PathAbsExamples.hs
app/test-pretty-exceptions/windows/System/Terminal.hs
package.yaml
pantry.cabal

This adds an optional executable `test-pretty-exceptions` (it is only built if flag `test-pretty-exceptions` is set; unset by default) to allow a person to test in a terminal (by visual inspection) the form of Pantry's pretty exceptions. The test is implemented as an executable rather than a 'test', because it is intended to be used by a person, not built and run automatically as part of CI, like a 'test' would.
Tested by building and running on Windows 11 and macOS 13.1. The CI has been extended to test the buildng of the executable.

Add an executable to test form of pretty exceptions

---

src/Pantry.hs

Currently, on GitHub, `fpco/stackage-content` redirects to `commercialhaskell/stackage-content`. This change is more direct.

Replace /fpco/ with /commercialhaskell/ in GitHub URL

---

src/Hackage/Security/Client/Repository/HttpLib/HttpClient.hs
src/Pantry.hs
src/Pantry/Archive.hs
src/Pantry/Casa.hs
src/Pantry/HTTP.hs
src/Pantry/Hackage.hs
src/Pantry/Internal/AesonExtended.hs
src/Pantry/Internal/StaticBytes.hs
src/Pantry/Storage.hs
src/Pantry/Tree.hs
src/Pantry/Types.hs

I went through the Hlint suggestions and applied those that seemed to be either sensible or, at least, not objectionable.
I hesitated over, but ultimately accepted:
*   'hoist not' (see also https://www.reddit.com/r/haskell/comments/z86sa2/why_is_hoisting_not_better/)
~~~haskell
guard $ all (not . T.all (== '.')) $ T.split (== '/') t -- Original
guard $ (not . any (T.all (== '.'))) $ T.split (== '/') t -- Suggestion
~~~
*   The use of infix and sections with a function with more than two arguments:
~~~haskell
fromWordsD = fromWordsForeign (\fptr len -> B.fromForeignPtr fptr 0 len) -- Original
fromWordsD = fromWordsForeign (`B.fromForeignPtr` 0) -- Suggestion
~~~

Apply certain Hlint suggestions

---

package.yaml
pantry.cabal

Fixes `could not execute: hspec-discover`:
```
$ cabal build all --enable-tests --enable-benchmarks
Build profile: -w ghc-9.4.5 -O1
In order, the following will be built (use -v for more details):
- pantry-0.8.3 (lib) (configuration changed)
- pantry-0.8.3 (test:spec) (first run)
Configuring library for pantry-0.8.3..
Preprocessing library for pantry-0.8.3..
Building library for pantry-0.8.3..
[18 of 19] Compiling Pantry.Repo
src/Pantry/Repo.hs:299:46: warning: [-Wdeprecations]
In the use of ‘hSupportsANSIWithoutEmulation’
(imported from System.Console.ANSI):
Deprecated: "See Haddock documentation and hSupportsANSI."
|
299 |           when osIsWindows $ void $ liftIO $ hSupportsANSIWithoutEmulation stdout
|                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[19 of …
```

Add build-tool: hspec-discover

---

src/Pantry/Types.hs

Since the last update, one Hackage root keyholder has retired (Johan Tibell) and two new ones have joined (Mathieu Boespflug and Joachim Breitner). The new root keys are authorized by the existing keyholders, so existing clients should give them the proper authority. However, new clients should have the current set of keyholders in the bootstrap set, which makes the system more robust against people leaving the process.
These changes remove the obsolete key, add the new keys, and improve the comments. Please check the keys against https://github.com/haskell-infra/hackage-root-keys before merging.
Please see #53 for a prior PR in the same vein.

Root key update 2023-06

---

src/Pantry.hs

This is only refactoring, and perhaps only a matter of personal taste, but it seemed to me that the use of `MaybeT` made the code shorter and clearer.

Use MaybeT, where appropriate

---

.github/workflows/tests.yml
ChangeLog.md
app/test-pretty-exceptions/Main.hs
int/Pantry/Types.hs
package.yaml
pantry.cabal
src/Pantry/Archive.hs
stack-ghc-9.4.8.yaml
stack.yaml
stack.yaml.lock

Also improve existing error messages referring to stack.yaml files.

Fix #117 Add error S-628 `LocalNoArchiveFileFound`

---

package.yaml
pantry.cabal

This lower bound is already implicit by the lower bound of `hpack`.
CI running here: https://github.com/andreasabel/pantry/pull/1

Bump lower bound of `base` to >= 4.13

---

ChangeLog.md
package.yaml
pantry.cabal
src/Pantry/Repo.hs

Being tested with a revised version of Stack.

Fix #129 loadRawPackage works with submodules on Windows

---

ChangeLog.md
package.yaml
pantry.cabal
src/Pantry/Hackage.hs

Tested by building and using Stack with a dependency on this version of pantry.

Fix #133 indexRelFile is function of cabalCacheLayout
